version: '3'

services:
  reverse-proxy:
    image: traefik:v2.9
    restart: always
    networks:
      - traefik-public
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./acme.json:/acme.json
      - ./dynamic-conf.yml:/dynamic-conf.yml
      - ./traefik-dashboard-users:/traefik-dashboard-users
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.mete0r.fr`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.tls.certresolver=default
      - traefik.http.routers.dashboard.middlewares=dashboard-auth
      - traefik.http.middlewares.dashboard-auth.basicauth.usersfile=/traefik-dashboard-users
networks:
  traefik-public:
    external: true